// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessagePayload } from "./MessagePayload";

export type Event = { type: string, time: string, from: string, message: MessagePayload | null, };
